# # Generated by Django 4.2.6 on 2023-10-12 19:50

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('DNA', '0001_initial'),
#     ]

#     operations = [
#         migrations.AddField(
#             model_name='user',
#             name='user',
#             field=models.DecimalField(decimal_places=2, default='null', max_digits=5),
#         ),
#         migrations.AddField(
#             model_name='user',
#             name='image',
#             field=models.ImageField(default='default_image.png', upload_to='u_images/'),
#         ),
#         migrations.AddField(
#             model_name='menu',
#             name='cost',
#             field=models.DecimalField(decimal_places=2, default='null', max_digits=5),
#         ),
#         migrations.AddField(
#             model_name='menu',
#             name='image',
#             field=models.ImageField(default='default_image.png', upload_to='menu_images/'),
#         ),
#         migrations.AddField(
#             model_name='types',
#             name='cost',
#             field=models.DecimalField(decimal_places=2, default='null', max_digits=5),
#         ),
#         migrations.AddField(
#             model_name='types',
#             name='image',
#             field=models.ImageField(default='default_image.png', upload_to='t_images/'),
#         ),
#         migrations.AddField(
#             model_name='basket',
#             name='cost',
#             field=models.DecimalField(decimal_places=2, default='null', max_digits=5),
#         ),
#         migrations.AddField(
#             model_name='basket',
#             name='image',
#             field=models.ImageField(default='default_image.png', upload_to='b_images/'),
#         ),
#     ]

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('DNA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.DecimalField(decimal_places=2, max_digits=5, default=0.0),  # Example default decimal value
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='u_images/default_image.png', upload_to='u_images/'),  # Example default image path
        ),
        migrations.AddField(
            model_name='menu',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, default=0.0),  # Example default decimal value
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='menu_images/default_image.png', upload_to='menu_images/'),  # Example default image path
        ),
        migrations.AddField(
            model_name='types',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, default=0.0),  # Example default decimal value
        ),
        migrations.AddField(
            model_name='types',
            name='image',
            field=models.ImageField(default='t_images/default_image.png', upload_to='t_images/'),  # Example default image path
        ),
        migrations.AddField(
            model_name='basket',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, default=0.0),  # Example default decimal value
        ),
        migrations.AddField(
            model_name='basket',
            name='image',
            field=models.ImageField(default='b_images/default_image.png', upload_to='b_images/'),  # Example default image path
        ),
    ]
