# Generated by Django 4.2.6 on 2023-10-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cold',
            name='cost',
            field=models.DecimalField(decimal_places=2, default='null', max_digits=5),
        ),
        migrations.AddField(
            model_name='cold',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to='c_images/'),
        ),
        migrations.AddField(
            model_name='dessert',
            name='cost',
            field=models.DecimalField(decimal_places=2, default='null', max_digits=5),
        ),
        migrations.AddField(
            model_name='dessert',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to='dessert_images/'),
        ),
        migrations.AddField(
            model_name='hot',
            name='cost',
            field=models.DecimalField(decimal_places=2, default='null', max_digits=5),
        ),
        migrations.AddField(
            model_name='hot',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to='h_images/'),
        ),
        migrations.AddField(
            model_name='snacks',
            name='cost',
            field=models.DecimalField(decimal_places=2, default='null', max_digits=5),
        ),
        migrations.AddField(
            model_name='snacks',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to='snack_images/'),
        ),
    ]
